"use client";
import {useEffect,useState} from "react";
type Category={id:number;code:string;name:string;visible:boolean};
export default function CategoryVisibility(){
 const [rows,setRows]=useState<Category[]>([]),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState<number|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/v1/store/category-visibility",{credentials:"include"}).then(async r=>{if(!r.ok)throw Error("No se pudieron consultar las categorías");setRows(await r.json())}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 async function update(row:Category){setBusy(row.id);setError("");try{const r=await fetch(`/api/v1/store/category-visibility/${row.id}`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({visible:!row.visible})});if(!r.ok)throw Error("No se pudo guardar el cambio");setRows(old=>old.map(item=>item.id===row.id?{...item,visible:!row.visible}:item))}catch(e){setError((e as Error).message)}finally{setBusy(null)}}
 return <section className="page"><h1>Visibilidad de categorías</h1><p>Selecciona qué categorías de primer nivel y sus artículos aparecen en el catálogo. Los cambios se guardan al marcar o desmarcar.</p><input className="input" aria-label="Filtrar categorías" placeholder="Buscar por código o categoría" value={query} onChange={e=>setQuery(e.target.value)}/>{error&&<p className="error" role="alert">{error}</p>}{loading?<p>Cargando categorías…</p>:<div className="visibility-table"><table><thead><tr><th>Código</th><th>Categoría</th><th>Visible</th></tr></thead><tbody>{rows.filter(row=>`${row.code} ${row.name}`.toLowerCase().includes(query.toLowerCase())).map(row=><tr key={row.id}><td>{row.code}</td><td>{row.name}</td><td><label><input type="checkbox" checked={row.visible} disabled={busy!==null} onChange={()=>update(row)} aria-label={`Mostrar ${row.name}`}/>{busy===row.id?"Guardando…":row.visible?"Visible":"Oculta"}</label></td></tr>)}</tbody></table></div>}</section>
}
